// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "playground",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "playground",
            targets: ["AppModule"],
            bundleIdentifier: "com.davySorokin.playground",
            teamIdentifier: "WA6VKCJAG5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/DenverCoder1/github-readme-streak-stats", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)